### ISSUE TITLE
Resolving shadow of sprites

### ISSUE THREAD

**Issue by yashica-patodia** [anmolharsh/ColorWow_Pygame1#19]
when two sprites come too close to one another then shadow one falls on the other

**Comment by yashica-patodia** [comment]
i want to address this issue

**Comment by anmolharsh** [comment]
sure, but i think shashvat has solved this already !
You may discuss with him in detail !!

**Comment by anmolharsh** [comment]
rather you can work over non-overlapping of sprites and also you may have seen that some sprites have really low speed so you can set an appropriate minimum and maximum speed
2. you may have seen that the player sprite goes off the screen, so you can add a lower boundary to the player sprite !
3. Also, you can add screen crawling feature that if the player sprite goes beyond the right screen boundary it comes inside the screen from the left boundary and vice-versa !

**Comment by yashica-patodia** [comment]
Yes I will work on it
